version: 1
disable_existing_loggers: False
formatters:
 simple:
   format: '%(asctime)s [%(name)s:%(lineno)d] [%(levelname)s]- %(message)s'
handlers:
 console:
   class: logging.StreamHandler
   level: DEBUG
   formatter: simple
   stream: ext://sys.stdout
 console_err:
   class: logging.StreamHandler
   level: DEBUG
   formatter: simple
   stream: ext://sys.stderr
 console_file:
   class : logging.handlers.TimedRotatingFileHandler
   formatter: simple
   filename: ../../logs/run.log
   interval: 1
   backupCount: 30
   encoding: utf8
   when: D
loggers:
 runLogger:
   level: INFO
   handlers: [console_file]
   propagate: 0
root:
 level: DEBUG
 handlers: [console_err]

