# FROM openeuler/openeuler:24.03
FROM registry.cn-hangzhou.aliyuncs.com/nriet/algorithm:tqradarmap_openeuler_24.03_linux_arm64

MAINTAINER Axiu <itzyx@vip.qq.com>

WORKDIR /app/TQRadarMap/dist/bin

COPY ./TQRadarMap/TQRadarMap_arm64/ /app/TQRadarMap




