# docker-image.yml
name: Publish Docker image   # workflow名称，可以在Github项目主页的【Actions】中看到所有的workflow
env:
  APP_NAME: algorithm
  DOCKERHUB_REPO: nriet/algorithm
on:   # 配置触发workflow的事件
  push:
    branches:   # master分支有push时触发此workflow
      - 'master'
    tags:       # tag更新时触发此workflow
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}  # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - 
        # name: Generate App Version
        # run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      # - name: NWP
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     file: NWP/Dockerfile.arm64
      #     platforms: |
      #       linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_REPO }}:nwp4.0
            
      # - name: kh9
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     file: kh9/Dockerfile.arm64
      #     platforms: |
      #       linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_REPO }}:kh9

      - name: metpy-tlnp
        uses: docker/build-push-action@v2 # docker build  & push
        with:
          context: metpy-tlnp/.
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:metpy-tlnp

      # - name: fy4b
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: fy4b/.
      #     platforms: |
      #       linux/amd64
      #       linux/arm64
      #     push: true
      #     tags: |
      #       nriet/fy4b:latest
      #       nriet/fy4b:python3.9-slim-v1

      # - name: algorithm:sedes-python3
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: sedes/.
      #     push: true
      #     tags: nriet/algorithm:python3-sedes

      # - name: algorithm:sedes-data
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: sedes-data/.
      #     push: true
      #     tags: nriet/algorithm:sedes-data-2023-11
          
      # - name: restcloud:2.5-slim-buster-zj-climate-miniconda
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: zj-climate-miniconda/.
      #     push: true
      #     tags: nriet/restcloud:2.5-slim-buster-zj-climate-miniconda
          
      # - name: algorithm:kylin10-zj-cpcs
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: zj-cpcs/.
      #     push: true
      #     tags: nriet/algorithm:kylin10-zj-cpcs
      # - name: algorithm:zj-cpcs
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: zj-cpcs/.
      #     push: true
      #     tags: nriet/algorithm:centos7.9.2009-zj-cpcs
      # - name: algorithm:ncl
      #   uses: docker/build-push-action@v2 # docker build  & push
      #   with:
      #     context: ncl/.
      #     push: true
      #     tags: nriet/algorithm:centos7.9.2009-ncl
